/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcbola;

import javax.swing.JProgressBar;

/**
 *
 * @author pc
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    panel mipanel;
    int valor1;
    public interfaz() {
        initComponents();
        
        
        setTitle( "Movimiento parabolico :v 9'-')9" );
        setLocationRelativeTo(null);
        //se crea instancia a panel de animacion y se añade a la interfaz
        mipanel=new panel( this.jPanel1.getSize() );
        this.jPanel1.add(mipanel);
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Progress1 = new javax.swing.JProgressBar();
        btnIni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 650));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        Progress1.setOrientation(1);
        Progress1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        Progress1.setStringPainted(true);
        Progress1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Progress1MouseDragged(evt);
            }
        });
        Progress1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Progress1MousePressed(evt);
            }
        });

        btnIni.setText("Iniciar");
        btnIni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniActionPerformed(evt);
            }
        });

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(623, 623, 623)
                        .addComponent(btnIni, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnIni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(Progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniActionPerformed
        mipanel.animar(true);
        panel.xran =(int) (Math.random() * 60)%1300;
        diana.X = 500;
        diana.X = (int) (Math.random()* (100 - 1180)+1180); 
        System.out.println("X: "+ diana.X);
        pelota.X = 50;
        //btnIni.setVisible(true);
        //btnIni.enable();
        mipanel.animar(true);
    }//GEN-LAST:event_btnIniActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        double ang, x, y, tmax, br1, br2, br3;
        int v0;
        pelota.t = 0;
        pelota.X = pelota.xemp;
        pelota.Y = pelota.yemp;
        x = (jPanel1.getMousePosition().x)-45;
        y = jPanel1.getMousePosition().y;
        pelota.ang = (45*Math.PI/180);
        br1 = (x*9.8);        
        v0=(int)Math.sqrt(br1/Math.sin(2*pelota.ang));        
        //System.out.println("v0 "+v0);
        pelota.v = v0;
        pelota.tmax=(2*v0*0.5/(9.8));
        //btnIni.setVisible(true);
        //btnIni.enable();
        //System.out.println("X "+x+" v0 "+v0+" t "+pelota.tmax+" ang "+Math.sin(pelota.ang));
        //System.out.println("tmax "+pelota.tmax);
        //System.out.println("x: "+x+" y: "+y+" v0: "+v0+" tmax: "+pelota.tmax);
        mipanel.animar(true);
       // System.out.println("x: "+x+" y: "+y+" ang: "+ang);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        //jLabel1.setText(string);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        jLabel1.setText("x: "+((int)jPanel1.getMousePosition().x-45)+" Y: "+(int)jPanel1.getMousePosition().y);
        //btnIni.setVisible(true);
        //btnIni.enable();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void Progress1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Progress1MousePressed
        valor1 = 100 - Progress1.getMousePosition().y;
        Progress1.setValue(valor1);
        Progress1.setString(valor1 + "%");
    }//GEN-LAST:event_Progress1MousePressed

    private void Progress1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Progress1MouseDragged
        // TODO add your handling code here:
        try{
            valor1 = 100 - Progress1.getMousePosition().y;
        Progress1.setValue(valor1);
        } catch (NullPointerException ex){
            
        }
        Progress1.setString(valor1 + "%");
    }//GEN-LAST:event_Progress1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progress1;
    private javax.swing.JButton btnIni;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
